kind: pipeline
type: docker
name: build

clone:
  disable: true


volumes:
  - name: node_modules
    host:
      path: /data/drones/data/node_modules


steps:
  - name: fetch-code
    image: node
    commands:
      - git clone http://Van:0.1234@192.168.100.136:3000/ims/ims.chin.ink.git .
      - echo 'git clone .....  completed'

  - name: build-code
    image: node
    depends_on: [fetch-code]
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
    commands:
      - ls
      - npm --version
      - npm config set registry https://registry.npmmirror.com
      - npm install
      - npm run build
      - cd ../

  - name: build-tags
    image: yxs970707/drone-web-tags
    depends_on: [fetch-code]
    settings:
      tags:
        - latest


  - name: build-image
    image: plugins/docker
    depends_on: [build-code]
#    commands:
#      - pwd
    settings:
      username:
        from_secret: docker_hub_id
      password:
        from_secret: docker_hub_password
      dockerfile: deploy/Dockerfile
      repo: inlins/lnmp-nginx
      tags:
        - latest
        - 0.0.1

