kind: pipeline
type: docker
name: build

clone:
  disable: true


volumes:
  - name: node_modules
    host:
      path: /data/drones/data/node_modules


steps:
  - name: fetch-code
    image: node
    commands:
      - git clone http://Van:0.1234@192.168.100.136:3000/ims/ims.chin.ink.git .
      - echo 'git clone .....  completed'

  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    depends_on: [ deploy-project ]
    settings:
      token: 6471ee9a262e5be891b93d52dde77ebd6e37e2f5c7051987d906747c200d737b
      secret: SEC7dc1e425e2948c31893d1e0c8915641fd0ea34376438052aba8debd75d6066b0
      debug: true
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
