kind: pipeline
type: ssh
name: default

server:
  host: 127.0.0.1
  user: van
  password: '0.1234'


platform:
  os: linux
  arch: amd64

steps:
  - name: greeting
    commands:
      - echo hello world