kind: pipeline
type: docker
name: build

clone:
  disable: true



steps:
  - name: greeting
    image: node
    commands:
      - git clone http://192.168.100.136:3000/ims/ims.chin.ink.git
      - git version
      - echo hello world
      - echo ok sucess