kind: pipeline
type: ssh
name: ssh-default

#platform:
#  os: linux
#  arch: amd64

# sssf

server:
  host: 192.168.100.136
  user: van
  password:
    from_secret: '0.1234'

steps:
  - name: greeting
    commands:
      - echo hello world
