import { defineStore } from "pinia";

import { loginApi } from "@/api/modules/ms/adminApi"



/**
 * @description: Login interface parameters
 */
export interface LoginParams {
    account: string;
    password: string;
}

import { listToTree } from "@/utils/helper/treeHelper";

import { getAuthCache, setAuthCache } from "@/utils/auth";


import {

    TOKEN_KEY,
    USER_INFO_KEY,
    NAV_MENUS_KEY,
    VIEW_NODES_KEY,
    AUTH_OPERATIONS,
} from "@/enums/cacheEnum";
import { UserInfo, AdminInfo } from "#/stores";
import { RoleEnum } from "@/enums/roleEnum";

import { router } from "@/router";

import { PageEnum } from "@/enums/pageEnum";
import { isArray } from "@/utils/is";

import { h } from "vue";
import { store } from "@/stores";

import { coerceTruthyTargetToArray } from "@/utils";
import Node from "@/utils/node";



interface AdminsState {
    token?: string;
    adminInfo: any;
    roleList: RoleEnum[];
    sessionTimeout?: boolean;
    lastUpdateTime: number;
    navMenus: any;
    filtering: boolean;
    lists: [];
    pagination: object;

    cuLoading: boolean;

}
// console.info('api.login =>',login);



 const useAdminStore = defineStore("admins", {
    state: (): AdminsState => ({
        // token
        token: undefined,
        adminInfo: {},
        lastUpdateTime: 0,
        sessionTimeout: false,
        roleList: [],
        navMenus: [],
        filtering: false,
        cuLoading: false,
        lists: [],
        pagination: {
            total: 0,
        },


    }),

    getters: {
        getAdminInfo(): UserInfo {
            return this.adminInfo || getAuthCache<UserInfo>(USER_INFO_KEY) || {};
        },
        getNavMenus() {
            if (this.navMenus.length > 0) {
                return this.navMenus;
            } else {
                const siderMenuProps = {
                    cachePrefix: "path-data-",
                    children: "children",
                    label: "name",
                    value: "id",
                    icon: "icon",
                    leaf: "leaf",
                    disabled: "disabled",
                };
                // const menus = getAuthCache(NAV_MENUS_KEY);

                const menus = [
                    {
                        id: 999,
                        pid: 0,
                        type: 1,
                        icon: "ant-design:home-outlined",
                        name: "分析页",
                        code: "dashboard_analysis",
                        options: {
                            name: "dashboard_analysis",
                            path: "dashboard/analysis",
                            file_path: "dashboard/analysis/index",
                            tree_path: 126,
                        },
                        sort: 1,
                        status: true,
                        created_at: "2022-01-25T12:58:52.000000Z",
                        updated_at: "2022-03-16T22:46:13.000000Z",
                        deleted_at: null,
                        children: [],
                        label: "分析页",
                        value: 999,
                        level: 1,
                    },
                    {
                        id: 126,
                        pid: 0,
                        type: 2,
                        icon: "ant-design:appstore-outlined",
                        name: "控制台",
                        code: "dashboard",
                        options: { name: "dashboard", path: "dashboard", tree_path: "0" },
                        sort: 0,
                        status: true,
                        created_at: "2018-05-24T19:32:54.000000Z",
                        updated_at: "2021-03-02T03:05:08.000000Z",
                        deleted_at: null,
                        children: [
                            {
                                id: 173,
                                pid: 126,
                                type: 1,
                                icon: "ant-design:home-outlined",
                                name: "分析页",
                                code: "dashboard_analysis",
                                options: {
                                    name: "dashboard_analysis",
                                    path: "dashboard/analysis",
                                    file_path: "dashboard/analysis/index",
                                    tree_path: 126,
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-01-25T12:58:52.000000Z",
                                updated_at: "2022-03-16T22:46:13.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "分析页",
                                value: 173,
                                level: 2,
                            },
                            {
                                id: 174,
                                pid: 126,
                                type: 1,
                                icon: "ant-design:home-outlined",
                                name: "工作台",
                                code: "dashboard_workbench",
                                options: {
                                    name: "dashboard_workbench",
                                    path: "dashboard/workbench",
                                    file_path: "dashboard/workbench/index",
                                    tree_path: 126,
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-01-25T12:58:52.000000Z",
                                updated_at: "2022-01-25T12:58:52.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "工作台",
                                value: 174,
                                level: 2,
                            },
                        ],
                        label: "控制台",
                        value: 126,
                        level: 1,
                    },
                    {
                        id: 153,
                        pid: 0,
                        type: 1,
                        icon: "ant-design:appstore-outlined",
                        name: "标签管理",
                        code: "tags",
                        options: {
                            meta: { title: "标签管理" },
                            name: "tags",
                            path: "tags/tags",
                            file_path: "tags/tags",
                            tree_path: 0,
                        },
                        sort: 1,
                        status: true,
                        created_at: "2020-11-04T12:17:56.000000Z",
                        updated_at: "2022-03-20T13:34:16.000000Z",
                        deleted_at: null,
                        children: [],
                        label: "标签管理",
                        value: 153,
                        level: 1,
                    },
                    {
                        id: 455,
                        pid: 0,
                        type: 2,
                        icon: "ant-design:appstore-outlined",
                        name: "开发管理",
                        code: "develops",
                        options: {
                            meta: { title: null },
                            name: null,
                            path: null,
                            file_path: null,
                            tree_path: 0,
                        },
                        sort: 1,
                        status: true,
                        created_at: "2022-06-21T18:07:38.000000Z",
                        updated_at: "2022-06-21T18:07:38.000000Z",
                        deleted_at: null,
                        children: [
                            {
                                id: 456,
                                pid: 455,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "页面配置",
                                code: "pages",
                                options: {
                                    meta: { title: "页面配置" },
                                    name: "develops_pages",
                                    path: "develops/pages",
                                    file_path: "develops/pages/index",
                                    tree_path: 0,
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-06-21T18:08:56.000000Z",
                                updated_at: "2022-06-21T18:10:02.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "页面配置",
                                value: 456,
                                level: 2,
                            },
                        ],
                        label: "开发管理",
                        value: 455,
                        level: 1,
                    },
                    {
                        id: 231,
                        pid: 0,
                        type: 2,
                        icon: "ant-design:appstore-outlined",
                        name: "数据统计",
                        code: "reports",
                        options: {
                            meta: { title: null },
                            name: null,
                            path: null,
                            file_path: null,
                            tree_path: 0,
                        },
                        sort: 1,
                        status: true,
                        created_at: "2022-04-06T12:43:30.000000Z",
                        updated_at: "2022-04-17T16:52:09.000000Z",
                        deleted_at: null,
                        children: [
                            {
                                id: 451,
                                pid: 231,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "扣卡记录",
                                code: "buckle_card_records",
                                options: {
                                    meta: { title: "扣卡记录" },
                                    name: "reports_buckle_cards_records",
                                    path: "reports/buckleCards",
                                    file_path: "reports/buckleCards/index",
                                    tree_path: 231,
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-06-12T15:15:42.000000Z",
                                updated_at: "2022-06-12T15:17:29.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "扣卡记录",
                                value: 451,
                                level: 2,
                            },
                            {
                                id: 458,
                                pid: 231,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "消费统计",
                                code: "consumes",
                                options: {
                                    meta: { title: "消费统计" },
                                    name: "consumes",
                                    path: "reports/consumes",
                                    file_path: "reports/consumes/index",
                                    tree_path: 231,
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-07-18T03:14:34.000000Z",
                                updated_at: "2022-07-18T03:16:55.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "消费统计",
                                value: 458,
                                level: 2,
                            },
                            {
                                id: 234,
                                pid: 231,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "预约统计",
                                code: "reports_appointments",
                                options: {
                                    meta: { title: "预约统计" },
                                    name: "appointments",
                                    path: "reports/appointments",
                                    file_path: "reports/appointments",
                                    tree_path: 231,
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-04-06T12:45:18.000000Z",
                                updated_at: "2022-04-17T15:49:36.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "预约统计",
                                value: 234,
                                level: 2,
                            },
                            {
                                id: 240,
                                pid: 231,
                                type: 2,
                                icon: "ant-design:appstore-outlined",
                                name: "业绩报表",
                                code: "performances_reports",
                                options: {
                                    meta: { title: "销售提成" },
                                    name: "royalties_sales",
                                    path: "reports/royalties/sales",
                                    file_path: "reports/royalties/sales/index",
                                    tree_path: 231,
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-04-17T16:51:10.000000Z",
                                updated_at: "2022-04-17T16:53:43.000000Z",
                                deleted_at: null,
                                children: [
                                    {
                                        id: 238,
                                        pid: 240,
                                        type: 1,
                                        icon: "ant-design:appstore-outlined",
                                        name: "销售业绩",
                                        code: "performances",
                                        options: {
                                            meta: { title: "业绩统计" },
                                            name: "performances_sales",
                                            path: "reports/performances/sales",
                                            file_path: "reports/performances/sales/index",
                                            tree_path: 231,
                                        },
                                        sort: 1,
                                        status: true,
                                        created_at: "2022-04-06T12:45:18.000000Z",
                                        updated_at: "2022-04-25T13:43:50.000000Z",
                                        deleted_at: null,
                                        children: [],
                                        label: "销售业绩",
                                        value: 238,
                                        level: 3,
                                    },
                                    {
                                        id: 241,
                                        pid: 240,
                                        type: 1,
                                        icon: "ant-design:appstore-outlined",
                                        name: "划扣业绩",
                                        code: "deducts_reports",
                                        options: {
                                            meta: { title: "业绩统计" },
                                            name: "performances_deducts",
                                            path: "reports/performances/deducts",
                                            file_path: "reports/performances/deducts/index",
                                            tree_path: 231,
                                        },
                                        sort: 1,
                                        status: true,
                                        created_at: "2022-04-06T12:45:18.000000Z",
                                        updated_at: "2022-04-17T16:57:24.000000Z",
                                        deleted_at: null,
                                        children: [],
                                        label: "划扣业绩",
                                        value: 241,
                                        level: 3,
                                    },
                                ],
                                label: "业绩报表",
                                value: 240,
                                level: 2,
                            },
                            {
                                id: 444,
                                pid: 231,
                                type: 2,
                                icon: "ant-design:appstore-outlined",
                                name: "提成报表",
                                code: "royalties",
                                options: {
                                    meta: { title: "销售提成" },
                                    name: "royalties_sales",
                                    path: "reports/royalties/sales",
                                    file_path: "reports/royalties/sales/index",
                                    tree_path: 231,
                                },
                                sort: 3,
                                status: true,
                                created_at: "2022-04-20T21:49:01.000000Z",
                                updated_at: "2022-04-20T22:03:02.000000Z",
                                deleted_at: null,
                                children: [
                                    {
                                        id: 445,
                                        pid: 444,
                                        type: 1,
                                        icon: "ant-design:appstore-outlined",
                                        name: "销售提成",
                                        code: "royalties_sales",
                                        options: {
                                            meta: { title: "销售提成" },
                                            name: "royalties_sales",
                                            path: "reports/royalties/sales",
                                            file_path: "reports/royalties/sales/index",
                                            tree_path: 231,
                                        },
                                        sort: 1,
                                        status: true,
                                        created_at: "2022-04-06T12:45:18.000000Z",
                                        updated_at: "2022-04-20T22:03:45.000000Z",
                                        deleted_at: null,
                                        children: [],
                                        label: "销售提成",
                                        value: 445,
                                        level: 3,
                                    },
                                    {
                                        id: 446,
                                        pid: 444,
                                        type: 1,
                                        icon: "ant-design:appstore-outlined",
                                        name: "操作提成",
                                        code: "royalties_deducts",
                                        options: {
                                            meta: { title: "操作提成" },
                                            name: "royalties_deducts",
                                            path: "reports/royalties/deducts",
                                            file_path: "reports/royalties/deducts/index",
                                            tree_path: 231,
                                        },
                                        sort: 2,
                                        status: true,
                                        created_at: "2022-04-06T12:45:18.000000Z",
                                        updated_at: "2022-04-25T13:46:01.000000Z",
                                        deleted_at: null,
                                        children: [],
                                        label: "操作提成",
                                        value: 446,
                                        level: 3,
                                    },
                                ],
                                label: "提成报表",
                                value: 444,
                                level: 2,
                            },
                        ],
                        label: "数据统计",
                        value: 231,
                        level: 1,
                    },
                    {
                        id: 236,
                        pid: 0,
                        type: 2,
                        icon: "ant-design:appstore-outlined",
                        name: "个人中心",
                        code: "mys",
                        options: {
                            meta: { title: null },
                            name: null,
                            path: null,
                            file_path: null,
                            tree_path: 0,
                        },
                        sort: 1,
                        status: true,
                        created_at: "2022-04-17T14:34:44.000000Z",
                        updated_at: "2022-04-17T14:34:44.000000Z",
                        deleted_at: null,
                        children: [
                            {
                                id: 237,
                                pid: 236,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "个人设置",
                                code: "personal_setting",
                                options: {
                                    meta: { title: "个人设置" },
                                    name: "profiles",
                                    path: "profiles",
                                    file_path: "profiles/index",
                                    tree_path: 236,
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-04-17T14:36:42.000000Z",
                                updated_at: "2022-04-17T14:36:42.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "个人设置",
                                value: 237,
                                level: 2,
                            },
                        ],
                        label: "个人中心",
                        value: 236,
                        level: 1,
                    },
                    {
                        id: 121,
                        pid: 0,
                        type: 2,
                        icon: "ant-design:appstore-outlined",
                        name: "会员",
                        code: "uses",
                        options: {
                            name: "systems_nodes",
                            path: "systems/nodes",
                            file_path: "users",
                            tree_path: "0",
                        },
                        sort: 3,
                        status: true,
                        created_at: "2019-03-27T15:43:35.000000Z",
                        updated_at: "2022-03-20T08:55:05.000000Z",
                        deleted_at: null,
                        children: [
                            {
                                id: 122,
                                pid: 121,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "顾客档案",
                                code: "users_lists",
                                options: {
                                    meta: { title: "顾客档案" },
                                    name: "users_lists",
                                    path: "users",
                                    file_path: "users/index",
                                    tree_path: "121",
                                },
                                sort: 1,
                                status: true,
                                created_at: "2019-03-27T15:44:27.000000Z",
                                updated_at: "2022-04-13T18:33:41.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "顾客档案",
                                value: 122,
                                level: 2,
                            },
                            {
                                id: 453,
                                pid: 121,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "卡券管理",
                                code: "cardManament",
                                options: {
                                    meta: { title: "卡券管理" },
                                    name: "cardManament",
                                    path: "cardManament",
                                    file_path: "cardManament/index",
                                    tree_path: "0,121",
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-06-27T13:34:55.000000Z",
                                updated_at: "2022-06-27T13:34:55.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "卡券管理",
                                value: 453,
                                level: 2,
                            },
                            {
                                id: 457,
                                pid: 121,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "顾客档案（新）",
                                code: "users_lists_new",
                                options: {
                                    meta: { title: "顾客档案（新）" },
                                    name: "users_lists_new",
                                    path: "usersnew",
                                    file_path: "users/indexNew",
                                    tree_path: "121",
                                },
                                sort: 1,
                                status: true,
                                created_at: "2019-03-27T15:44:27.000000Z",
                                updated_at: "2022-07-11T14:34:26.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "顾客档案（新）",
                                value: 457,
                                level: 2,
                            },
                            {
                                id: 123,
                                pid: 121,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "预约挂号",
                                code: "reservations",
                                options: {
                                    meta: { title: "预约挂号" },
                                    name: "reservations",
                                    path: "reservations",
                                    file_path: "reservations/index",
                                    tree_path: "121",
                                },
                                sort: 2,
                                status: true,
                                created_at: "2019-03-27T19:25:13.000000Z",
                                updated_at: "2022-04-13T18:33:35.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "预约挂号",
                                value: 123,
                                level: 2,
                            },
                            {
                                id: 129,
                                pid: 121,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "就诊记录",
                                code: "consults",
                                options: {
                                    meta: { title: "就诊记录" },
                                    name: "users_consults",
                                    path: "users/consults",
                                    file_path: "consults/index",
                                    tree_path: "121",
                                },
                                sort: 3,
                                status: true,
                                created_at: "2020-11-04T12:17:56.000000Z",
                                updated_at: "2022-04-13T18:34:07.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "就诊记录",
                                value: 129,
                                level: 2,
                            },
                            {
                                id: 131,
                                pid: 121,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "划扣管理",
                                code: "deducts",
                                options: {
                                    meta: { title: "划扣管理" },
                                    name: "users_deducts",
                                    path: "users/deducts",
                                    file_path: "deducts/index",
                                    tree_path: "121",
                                },
                                sort: 4,
                                status: true,
                                created_at: null,
                                updated_at: "2022-04-13T18:34:28.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "划扣管理",
                                value: 131,
                                level: 2,
                            },
                            {
                                id: 143,
                                pid: 121,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "划扣记录",
                                code: "users_deduct",
                                options: {
                                    meta: { title: "划扣记录" },
                                    name: "deduct_records",
                                    path: "deducts/records",
                                    file_path: "deductRecords/index",
                                    tree_path: "121",
                                },
                                sort: 5,
                                status: true,
                                created_at: "2021-03-28T11:43:24.000000Z",
                                updated_at: "2022-04-14T18:48:08.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "划扣记录",
                                value: 143,
                                level: 2,
                            },
                            {
                                id: 146,
                                pid: 121,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "回访计划",
                                code: "plans",
                                options: {
                                    meta: { title: "回访记划" },
                                    name: "users_plans",
                                    path: "users/plans",
                                    file_path: "users/plans",
                                    tree_path: "121",
                                },
                                sort: 6,
                                status: true,
                                created_at: "2020-11-04T12:17:56.000000Z",
                                updated_at: "2022-07-10T19:39:31.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "回访计划",
                                value: 146,
                                level: 2,
                            },
                            {
                                id: 130,
                                pid: 121,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "回访记录",
                                code: "revisits",
                                options: {
                                    meta: { title: "回访记录" },
                                    name: "users_revisits",
                                    path: "users/revisits",
                                    file_path: "users/revisits",
                                    tree_path: "121",
                                },
                                sort: 7,
                                status: true,
                                created_at: "2020-11-04T12:17:56.000000Z",
                                updated_at: "2022-04-14T18:48:03.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "回访记录",
                                value: 130,
                                level: 2,
                            },
                        ],
                        label: "会员",
                        value: 121,
                        level: 1,
                    },
                    {
                        id: 166,
                        pid: 0,
                        type: 2,
                        icon: "ant-design:appstore-outlined",
                        name: "产品",
                        code: "products",
                        options: { name: null, path: null, tree_path: 0 },
                        sort: 3,
                        status: true,
                        created_at: "2022-01-19T13:40:40.000000Z",
                        updated_at: "2022-01-19T13:40:40.000000Z",
                        deleted_at: null,
                        children: [
                            {
                                id: 163,
                                pid: 166,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "物料管理",
                                code: "material",
                                options: {
                                    meta: { title: "物料管理" },
                                    name: "materials",
                                    path: "materials",
                                    file_path: "materials/index",
                                    tree_path: "0",
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-01-18T20:38:46.000000Z",
                                updated_at: "2022-03-17T17:52:31.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "物料管理",
                                value: 163,
                                level: 2,
                            },
                            {
                                id: 168,
                                pid: 166,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "产品管理",
                                code: "prods",
                                options: {
                                    meta: { title: "产品管理" },
                                    name: "products",
                                    path: "products",
                                    file_path: "products/index",
                                    tree_path: 166,
                                },
                                sort: 2,
                                status: true,
                                created_at: "2022-01-19T13:41:33.000000Z",
                                updated_at: "2022-03-21T06:57:43.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "产品管理",
                                value: 168,
                                level: 2,
                            },
                            {
                                id: 169,
                                pid: 166,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "项目管理",
                                code: "projects",
                                options: {
                                    meta: { title: "项目管理" },
                                    name: "projects",
                                    path: "projects",
                                    file_path: "projects/index",
                                    tree_path: 166,
                                },
                                sort: 3,
                                status: true,
                                created_at: "2022-01-25T12:58:52.000000Z",
                                updated_at: "2022-03-21T06:57:22.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "项目管理",
                                value: 169,
                                level: 2,
                            },
                        ],
                        label: "产品",
                        value: 166,
                        level: 1,
                    },
                    {
                        id: 170,
                        pid: 0,
                        type: 2,
                        icon: "ant-design:appstore-outlined",
                        name: "库房管理",
                        code: "warehouses",
                        options: { name: null, path: null, tree_path: 0 },
                        sort: 3,
                        status: true,
                        created_at: "2022-01-19T13:40:40.000000Z",
                        updated_at: "2022-01-19T13:40:40.000000Z",
                        deleted_at: null,
                        children: [
                            {
                                id: 447,
                                pid: 170,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "库房统计",
                                code: "stocks_statistics",
                                options: {
                                    meta: { title: "库房统计" },
                                    name: "stocks_statistics",
                                    path: "stocks/statistics",
                                    file_path: "stocks/statistics/index",
                                    tree_path: 170,
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-04-25T17:02:11.000000Z",
                                updated_at: "2022-04-25T17:02:11.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "库房统计",
                                value: 447,
                                level: 2,
                            },
                            {
                                id: 214,
                                pid: 170,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "供应商管理",
                                code: "suppliers",
                                options: {
                                    meta: { title: "供应商管理" },
                                    name: "suppliers",
                                    path: "suppliers/index",
                                    file_path: "suppliers/index",
                                    tree_path: 0,
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-03-20T06:22:37.000000Z",
                                updated_at: "2022-03-20T06:39:59.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "供应商管理",
                                value: 214,
                                level: 2,
                            },
                            {
                                id: 242,
                                pid: 170,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "入库记录",
                                code: "outbound",
                                options: {
                                    meta: { title: "入库管理" },
                                    name: "outbound",
                                    path: "warehouses/outbound",
                                    file_path: "warehouses/outbound",
                                    tree_path: 170,
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-04-17T15:04:24.000000Z",
                                updated_at: "2022-04-17T20:13:00.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "入库记录",
                                value: 242,
                                level: 2,
                            },
                            {
                                id: 243,
                                pid: 170,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "出库记录",
                                code: "outs",
                                options: {
                                    meta: { title: "出库记录" },
                                    name: "outs",
                                    path: "warehouses/outs",
                                    file_path: "stocks/outs/index",
                                    tree_path: 170,
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-04-17T15:04:24.000000Z",
                                updated_at: "2022-04-17T20:42:28.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "出库记录",
                                value: 243,
                                level: 2,
                            },
                            {
                                id: 171,
                                pid: 170,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "采购管理",
                                code: "warehouses_purchases",
                                options: {
                                    meta: { title: "采购管理" },
                                    name: "warehouses_purchases",
                                    path: "warehouses/purchases",
                                    file_path: "purchases/index",
                                    tree_path: 170,
                                },
                                sort: 2,
                                status: true,
                                created_at: "2022-01-19T13:41:33.000000Z",
                                updated_at: "2022-03-27T15:51:45.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "采购管理",
                                value: 171,
                                level: 2,
                            },
                            {
                                id: 172,
                                pid: 170,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "库存管理",
                                code: "stocks",
                                options: {
                                    meta: { title: "库存管理" },
                                    name: "stocks",
                                    path: "stocks",
                                    file_path: "stocks/index",
                                    tree_path: 170,
                                },
                                sort: 3,
                                status: true,
                                created_at: "2022-01-25T12:58:52.000000Z",
                                updated_at: "2022-04-05T15:14:01.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "库存管理",
                                value: 172,
                                level: 2,
                            },
                        ],
                        label: "库房管理",
                        value: 170,
                        level: 1,
                    },
                    {
                        id: 1,
                        pid: 0,
                        type: 2,
                        icon: "ant-design:appstore-outlined",
                        name: "系统",
                        code: "systems",
                        options: { tree_path: "0" },
                        sort: 4,
                        status: true,
                        created_at: "2018-05-24T19:32:54.000000Z",
                        updated_at: "2021-03-02T03:40:27.000000Z",
                        deleted_at: null,
                        children: [
                            {
                                id: 3,
                                pid: 1,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "节点管理",
                                code: "node",
                                options: {
                                    meta: { title: "节点管理" },
                                    name: "systems_nodes",
                                    path: "systems/nodes",
                                    file_path: "systems/nodes",
                                    tree_path: "1",
                                },
                                sort: 0,
                                status: true,
                                created_at: "2018-05-24T19:32:54.000000Z",
                                updated_at: "2022-03-20T09:59:24.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "节点管理",
                                value: 3,
                                level: 2,
                            },
                            {
                                id: 95,
                                pid: 1,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "组织机构",
                                code: "systems_departments",
                                options: {
                                    meta: { title: "组织机构" },
                                    name: "systems_departments",
                                    path: "systems/departments",
                                    file_path: "systems/departments",
                                    tree_path: "1",
                                },
                                sort: 0,
                                status: true,
                                created_at: "2019-03-06T03:55:50.000000Z",
                                updated_at: "2022-03-20T12:27:54.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "组织机构",
                                value: 95,
                                level: 2,
                            },
                            {
                                id: 104,
                                pid: 1,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "角色管理",
                                code: "roles",
                                options: {
                                    meta: { title: "角色管理" },
                                    name: "systems_roles",
                                    path: "systems/roles",
                                    file_path: "systems/roles",
                                    tree_path: "1",
                                },
                                sort: 0,
                                status: true,
                                created_at: "2019-03-10T23:55:43.000000Z",
                                updated_at: "2022-03-20T11:17:35.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "角色管理",
                                value: 104,
                                level: 2,
                            },
                            {
                                id: 128,
                                pid: 1,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "分类管理",
                                code: "categories",
                                options: {
                                    meta: { title: "分类管理" },
                                    name: "systems_categories",
                                    path: "systems/categories",
                                    file_path: "systems/categories",
                                    tree_path: "121",
                                },
                                sort: 1,
                                status: true,
                                created_at: "2020-11-04T12:17:56.000000Z",
                                updated_at: "2022-03-17T18:56:09.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "分类管理",
                                value: 128,
                                level: 2,
                            },
                            {
                                id: 213,
                                pid: 1,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "分类类型",
                                code: "categoryTypes",
                                options: {
                                    meta: { title: "分类类型" },
                                    name: "systems_categories_types",
                                    path: "systems/categories/types",
                                    file_path: "systems/categoryTypes",
                                    tree_path: "0,1",
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-03-17T20:25:57.000000Z",
                                updated_at: "2022-03-17T20:25:57.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "分类类型",
                                value: 213,
                                level: 2,
                            },
                            {
                                id: 230,
                                pid: 1,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "登录日志",
                                code: "login_log3",
                                options: {
                                    meta: { title: "登录日志" },
                                    name: "login_log",
                                    path: "systems/loginlog",
                                    file_path: "systems/loginlog",
                                    tree_path: "0,1",
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-03-21T09:59:55.000000Z",
                                updated_at: "2022-03-21T10:23:22.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "登录日志",
                                value: 230,
                                level: 2,
                            },
                            {
                                id: 235,
                                pid: 1,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "系统配置",
                                code: "configurations",
                                options: {
                                    meta: { title: "系统配置" },
                                    name: "configurations",
                                    path: "systems/configurations",
                                    file_path: "configurations/index",
                                    tree_path: "0,1",
                                },
                                sort: 1,
                                status: true,
                                created_at: "2022-04-07T18:38:12.000000Z",
                                updated_at: "2022-04-07T18:38:12.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "系统配置",
                                value: 235,
                                level: 2,
                            },
                            {
                                id: 93,
                                pid: 1,
                                type: 1,
                                icon: "ant-design:appstore-outlined",
                                name: "用户管理",
                                code: "systems_admins",
                                options: {
                                    meta: { title: "用户管理" },
                                    name: "systems_admins",
                                    path: "systems/admins",
                                    file_path: "systems/admins",
                                    tree_path: "1",
                                },
                                sort: 2,
                                status: true,
                                created_at: "2019-03-03T04:21:21.000000Z",
                                updated_at: "2022-03-21T05:28:30.000000Z",
                                deleted_at: null,
                                children: [],
                                label: "用户管理",
                                value: 93,
                                level: 2,
                            },
                        ],
                        label: "系统",
                        value: 1,
                        level: 1,
                    },
                ];
                // console.info('menus => -============------',menus);
                const truthyedNavMenus = coerceTruthyTargetToArray(menus).map(
                    (nodeData) => new Node(nodeData, siderMenuProps)
                );
                return truthyedNavMenus;
            }
        },

    },

    actions: {
        login(data:any) {
            console.info('adminStore.login.data =>',data);

            loginApi(data).then(rsp=>{
                console.info('rsp =>',rsp);
            })

        }
    },
});

export default useAdminStore;

// Need to be used outside the setup
export function useAdminStoreWithOut() {
    return useAdminStore(store);
}
