import { defineStore } from "pinia";

import { getAuthCache } from "@/utils/auth";

import type { LayoutsConfig } from "#/config";

import { router } from "@/router";

import type { ThemeEnum } from "@/enums/appEnum";
import { LAYOUTS_CFG_KEY } from "@/enums/cacheEnum";
import { Persistent } from "@/utils/cache/persistent";
import { darkMode } from "@/settings/stylesSetting";
import { deepMerge } from "@/utils";

// import api from "/@/api/purchases";

interface layoutsState {
    layoutsConfig: LayoutsConfig;
    tiggerIcon?: string;
    collapsed: boolean | undefined;
    headerBrandVisible: boolean;
    selectedKeys: number[];
    menuSelectedKeys: number[];
    openKeys: number[];
    preOpenKeys: number[];
    navMenus: number[];
    topMenus: any[];
    statuses: any[];
    tabBarTabs: any[];
    breadcrumbRoutes: any[];
}

const useLayoutsStore = defineStore("layouts", {
    state: (): layoutsState => {
        return {
            // layoutsConfig:
            //     Persistent.getLocal(LAYOUTS_CFG_KEY) || ({} as LayoutsConfig),

            layoutsConfig: {
              msLayout:{
                  inlineCollapsed:false,
                  asiderDrawerVisible:false,
              }
            },
            tiggerIcon: "ant-design:menu-fold-outlined",
            collapsed: undefined,
            headerBrandVisible: false,
            selectedKeys: [999],
            menuSelectedKeys: [999],
            openKeys: [],
            preOpenKeys: [],
            navMenus: [],

            topMenus: [
                {
                    id: 231,
                    pid: 0,
                    type: 2,
                    icon: "ant-design:appstore-outlined",
                    name: "数据统计",
                    code: "reports",
                    options: {
                        meta: { title: null },
                        name: null,
                        path: null,
                        file_path: null,
                        tree_path: 0,
                    },
                    sort: 1,
                    status: true,
                    created_at: "2022-04-06T12:43:30.000000Z",
                    updated_at: "2022-04-17T16:52:09.000000Z",
                    deleted_at: null,
                    children: [
                        {
                            id: 451,
                            pid: 231,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "扣卡记录",
                            code: "buckle_card_records",
                            options: {
                                meta: { title: "扣卡记录" },
                                name: "reports_buckle_cards_records",
                                path: "reports/buckleCards",
                                file_path: "reports/buckleCards/index",
                                tree_path: 231,
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-06-12T15:15:42.000000Z",
                            updated_at: "2022-06-12T15:17:29.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "扣卡记录",
                            value: 451,
                            level: 2,
                        },
                        {
                            id: 458,
                            pid: 231,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "消费统计",
                            code: "consumes",
                            options: {
                                meta: { title: "消费统计" },
                                name: "consumes",
                                path: "reports/consumes",
                                file_path: "reports/consumes/index",
                                tree_path: 231,
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-07-18T03:14:34.000000Z",
                            updated_at: "2022-07-18T03:16:55.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "消费统计",
                            value: 458,
                            level: 2,
                        },
                        {
                            id: 234,
                            pid: 231,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "预约统计",
                            code: "reports_appointments",
                            options: {
                                meta: { title: "预约统计" },
                                name: "appointments",
                                path: "reports/appointments",
                                file_path: "reports/appointments",
                                tree_path: 231,
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-04-06T12:45:18.000000Z",
                            updated_at: "2022-04-17T15:49:36.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "预约统计",
                            value: 234,
                            level: 2,
                        },
                        {
                            id: 240,
                            pid: 231,
                            type: 2,
                            icon: "ant-design:appstore-outlined",
                            name: "业绩报表",
                            code: "performances_reports",
                            options: {
                                meta: { title: "销售提成" },
                                name: "royalties_sales",
                                path: "reports/royalties/sales",
                                file_path: "reports/royalties/sales/index",
                                tree_path: 231,
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-04-17T16:51:10.000000Z",
                            updated_at: "2022-04-17T16:53:43.000000Z",
                            deleted_at: null,
                            children: [
                                {
                                    id: 238,
                                    pid: 240,
                                    type: 1,
                                    icon: "ant-design:appstore-outlined",
                                    name: "销售业绩",
                                    code: "performances",
                                    options: {
                                        meta: { title: "业绩统计" },
                                        name: "performances_sales",
                                        path: "reports/performances/sales",
                                        file_path: "reports/performances/sales/index",
                                        tree_path: 231,
                                    },
                                    sort: 1,
                                    status: true,
                                    created_at: "2022-04-06T12:45:18.000000Z",
                                    updated_at: "2022-04-25T13:43:50.000000Z",
                                    deleted_at: null,
                                    children: [],
                                    label: "销售业绩",
                                    value: 238,
                                    level: 3,
                                },
                                {
                                    id: 241,
                                    pid: 240,
                                    type: 1,
                                    icon: "ant-design:appstore-outlined",
                                    name: "划扣业绩",
                                    code: "deducts_reports",
                                    options: {
                                        meta: { title: "业绩统计" },
                                        name: "performances_deducts",
                                        path: "reports/performances/deducts",
                                        file_path: "reports/performances/deducts/index",
                                        tree_path: 231,
                                    },
                                    sort: 1,
                                    status: true,
                                    created_at: "2022-04-06T12:45:18.000000Z",
                                    updated_at: "2022-04-17T16:57:24.000000Z",
                                    deleted_at: null,
                                    children: [],
                                    label: "划扣业绩",
                                    value: 241,
                                    level: 3,
                                },
                            ],
                            label: "业绩报表",
                            value: 240,
                            level: 2,
                        },
                        {
                            id: 444,
                            pid: 231,
                            type: 2,
                            icon: "ant-design:appstore-outlined",
                            name: "提成报表",
                            code: "royalties",
                            options: {
                                meta: { title: "销售提成" },
                                name: "royalties_sales",
                                path: "reports/royalties/sales",
                                file_path: "reports/royalties/sales/index",
                                tree_path: 231,
                            },
                            sort: 3,
                            status: true,
                            created_at: "2022-04-20T21:49:01.000000Z",
                            updated_at: "2022-04-20T22:03:02.000000Z",
                            deleted_at: null,
                            children: [
                                {
                                    id: 445,
                                    pid: 444,
                                    type: 1,
                                    icon: "ant-design:appstore-outlined",
                                    name: "销售提成",
                                    code: "royalties_sales",
                                    options: {
                                        meta: { title: "销售提成" },
                                        name: "royalties_sales",
                                        path: "reports/royalties/sales",
                                        file_path: "reports/royalties/sales/index",
                                        tree_path: 231,
                                    },
                                    sort: 1,
                                    status: true,
                                    created_at: "2022-04-06T12:45:18.000000Z",
                                    updated_at: "2022-04-20T22:03:45.000000Z",
                                    deleted_at: null,
                                    children: [],
                                    label: "销售提成",
                                    value: 445,
                                    level: 3,
                                },
                                {
                                    id: 446,
                                    pid: 444,
                                    type: 1,
                                    icon: "ant-design:appstore-outlined",
                                    name: "操作提成",
                                    code: "royalties_deducts",
                                    options: {
                                        meta: { title: "操作提成" },
                                        name: "royalties_deducts",
                                        path: "reports/royalties/deducts",
                                        file_path: "reports/royalties/deducts/index",
                                        tree_path: 231,
                                    },
                                    sort: 2,
                                    status: true,
                                    created_at: "2022-04-06T12:45:18.000000Z",
                                    updated_at: "2022-04-25T13:46:01.000000Z",
                                    deleted_at: null,
                                    children: [],
                                    label: "操作提成",
                                    value: 446,
                                    level: 3,
                                },
                            ],
                            label: "提成报表",
                            value: 444,
                            level: 2,
                        },
                    ],
                    label: "数据统计",
                    value: 231,
                    level: 1,
                },
                {
                    id: 170,
                    pid: 0,
                    type: 2,
                    icon: "ant-design:appstore-outlined",
                    name: "库房管理",
                    code: "warehouses",
                    options: { name: null, path: null, tree_path: 0 },
                    sort: 3,
                    status: true,
                    created_at: "2022-01-19T13:40:40.000000Z",
                    updated_at: "2022-01-19T13:40:40.000000Z",
                    deleted_at: null,
                    children: [
                        {
                            id: 447,
                            pid: 170,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "库房统计",
                            code: "stocks_statistics",
                            options: {
                                meta: { title: "库房统计" },
                                name: "stocks_statistics",
                                path: "stocks/statistics",
                                file_path: "stocks/statistics/index",
                                tree_path: 170,
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-04-25T17:02:11.000000Z",
                            updated_at: "2022-04-25T17:02:11.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "库房统计",
                            value: 447,
                            level: 2,
                        },
                        {
                            id: 214,
                            pid: 170,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "供应商管理",
                            code: "suppliers",
                            options: {
                                meta: { title: "供应商管理" },
                                name: "suppliers",
                                path: "suppliers/index",
                                file_path: "suppliers/index",
                                tree_path: 0,
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-03-20T06:22:37.000000Z",
                            updated_at: "2022-03-20T06:39:59.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "供应商管理",
                            value: 214,
                            level: 2,
                        },
                        {
                            id: 242,
                            pid: 170,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "入库记录",
                            code: "outbound",
                            options: {
                                meta: { title: "入库管理" },
                                name: "outbound",
                                path: "warehouses/outbound",
                                file_path: "warehouses/outbound",
                                tree_path: 170,
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-04-17T15:04:24.000000Z",
                            updated_at: "2022-04-17T20:13:00.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "入库记录",
                            value: 242,
                            level: 2,
                        },
                        {
                            id: 243,
                            pid: 170,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "出库记录",
                            code: "outs",
                            options: {
                                meta: { title: "出库记录" },
                                name: "outs",
                                path: "warehouses/outs",
                                file_path: "stocks/outs/index",
                                tree_path: 170,
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-04-17T15:04:24.000000Z",
                            updated_at: "2022-04-17T20:42:28.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "出库记录",
                            value: 243,
                            level: 2,
                        },
                        {
                            id: 171,
                            pid: 170,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "采购管理",
                            code: "warehouses_purchases",
                            options: {
                                meta: { title: "采购管理" },
                                name: "warehouses_purchases",
                                path: "warehouses/purchases",
                                file_path: "purchases/index",
                                tree_path: 170,
                            },
                            sort: 2,
                            status: true,
                            created_at: "2022-01-19T13:41:33.000000Z",
                            updated_at: "2022-03-27T15:51:45.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "采购管理",
                            value: 171,
                            level: 2,
                        },
                        {
                            id: 172,
                            pid: 170,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "库存管理",
                            code: "stocks",
                            options: {
                                meta: { title: "库存管理" },
                                name: "stocks",
                                path: "stocks",
                                file_path: "stocks/index",
                                tree_path: 170,
                            },
                            sort: 3,
                            status: true,
                            created_at: "2022-01-25T12:58:52.000000Z",
                            updated_at: "2022-04-05T15:14:01.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "库存管理",
                            value: 172,
                            level: 2,
                        },
                    ],
                    label: "库房管理",
                    value: 170,
                    level: 1,
                },
                {
                    id: 1,
                    pid: 0,
                    type: 2,
                    icon: "ant-design:appstore-outlined",
                    name: "系统设置",
                    code: "systems",
                    options: { tree_path: "0" },
                    sort: 4,
                    status: true,
                    created_at: "2018-05-24T19:32:54.000000Z",
                    updated_at: "2021-03-02T03:40:27.000000Z",
                    deleted_at: null,
                    children: [
                        {
                            id: 3,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "节点管理",
                            code: "node",
                            options: {
                                meta: { title: "节点管理" },
                                name: "systems_nodes",
                                path: "systems/nodes",
                                file_path: "systems/nodes",
                                tree_path: "1",
                            },
                            sort: 0,
                            status: true,
                            created_at: "2018-05-24T19:32:54.000000Z",
                            updated_at: "2022-03-20T09:59:24.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "节点管理",
                            value: 3,
                            level: 2,
                        },
                        {
                            id: 95,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "组织机构",
                            code: "systems_departments",
                            options: {
                                meta: { title: "组织机构" },
                                name: "systems_departments",
                                path: "systems/departments",
                                file_path: "systems/departments",
                                tree_path: "1",
                            },
                            sort: 0,
                            status: true,
                            created_at: "2019-03-06T03:55:50.000000Z",
                            updated_at: "2022-03-20T12:27:54.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "组织机构",
                            value: 95,
                            level: 2,
                        },
                        {
                            id: 104,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "角色管理",
                            code: "roles",
                            options: {
                                meta: { title: "角色管理" },
                                name: "systems_roles",
                                path: "systems/roles",
                                file_path: "systems/roles",
                                tree_path: "1",
                            },
                            sort: 0,
                            status: true,
                            created_at: "2019-03-10T23:55:43.000000Z",
                            updated_at: "2022-03-20T11:17:35.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "角色管理",
                            value: 104,
                            level: 2,
                        },
                        {
                            id: 128,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "分类管理",
                            code: "categories",
                            options: {
                                meta: { title: "分类管理" },
                                name: "systems_categories",
                                path: "systems/categories",
                                file_path: "systems/categories",
                                tree_path: "121",
                            },
                            sort: 1,
                            status: true,
                            created_at: "2020-11-04T12:17:56.000000Z",
                            updated_at: "2022-03-17T18:56:09.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "分类管理",
                            value: 128,
                            level: 2,
                        },
                        {
                            id: 213,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "分类类型",
                            code: "categoryTypes",
                            options: {
                                meta: { title: "分类类型" },
                                name: "systems_categories_types",
                                path: "systems/categories/types",
                                file_path: "systems/categoryTypes",
                                tree_path: "0,1",
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-03-17T20:25:57.000000Z",
                            updated_at: "2022-03-17T20:25:57.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "分类类型",
                            value: 213,
                            level: 2,
                        },
                        {
                            id: 230,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "登录日志",
                            code: "login_log3",
                            options: {
                                meta: { title: "登录日志" },
                                name: "login_log",
                                path: "systems/loginlog",
                                file_path: "systems/loginlog",
                                tree_path: "0,1",
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-03-21T09:59:55.000000Z",
                            updated_at: "2022-03-21T10:23:22.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "登录日志",
                            value: 230,
                            level: 2,
                        },
                        {
                            id: 235,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "系统配置",
                            code: "configurations",
                            options: {
                                meta: { title: "系统配置" },
                                name: "configurations",
                                path: "systems/configurations",
                                file_path: "configurations/index",
                                tree_path: "0,1",
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-04-07T18:38:12.000000Z",
                            updated_at: "2022-04-07T18:38:12.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "系统配置",
                            value: 235,
                            level: 2,
                        },
                        {
                            id: 93,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "用户管理",
                            code: "systems_admins",
                            options: {
                                meta: { title: "用户管理" },
                                name: "systems_admins",
                                path: "systems/admins",
                                file_path: "systems/admins",
                                tree_path: "1",
                            },
                            sort: 2,
                            status: true,
                            created_at: "2019-03-03T04:21:21.000000Z",
                            updated_at: "2022-03-21T05:28:30.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "用户管理",
                            value: 93,
                            level: 2,
                        },
                    ],
                    label: "系统",
                    value: 1,
                    level: 1,
                },
                {
                    id: 18989,
                    pid: 0,
                    type: 2,
                    icon: "ant-design:appstore-outlined",
                    name: "其他设置",
                    code: "systems",
                    options: { tree_path: "0" },
                    sort: 4,
                    status: true,
                    created_at: "2018-05-24T19:32:54.000000Z",
                    updated_at: "2021-03-02T03:40:27.000000Z",
                    deleted_at: null,
                    children: [
                        {
                            id: 3,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "节点管理",
                            code: "node",
                            options: {
                                meta: { title: "节点管理" },
                                name: "systems_nodes",
                                path: "systems/nodes",
                                file_path: "systems/nodes",
                                tree_path: "1",
                            },
                            sort: 0,
                            status: true,
                            created_at: "2018-05-24T19:32:54.000000Z",
                            updated_at: "2022-03-20T09:59:24.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "节点管理",
                            value: 3,
                            level: 2,
                        },
                        {
                            id: 95,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "组织机构",
                            code: "systems_departments",
                            options: {
                                meta: { title: "组织机构" },
                                name: "systems_departments",
                                path: "systems/departments",
                                file_path: "systems/departments",
                                tree_path: "1",
                            },
                            sort: 0,
                            status: true,
                            created_at: "2019-03-06T03:55:50.000000Z",
                            updated_at: "2022-03-20T12:27:54.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "组织机构",
                            value: 95,
                            level: 2,
                        },
                        {
                            id: 104,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "角色管理",
                            code: "roles",
                            options: {
                                meta: { title: "角色管理" },
                                name: "systems_roles",
                                path: "systems/roles",
                                file_path: "systems/roles",
                                tree_path: "1",
                            },
                            sort: 0,
                            status: true,
                            created_at: "2019-03-10T23:55:43.000000Z",
                            updated_at: "2022-03-20T11:17:35.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "角色管理",
                            value: 104,
                            level: 2,
                        },
                        {
                            id: 128,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "分类管理",
                            code: "categories",
                            options: {
                                meta: { title: "分类管理" },
                                name: "systems_categories",
                                path: "systems/categories",
                                file_path: "systems/categories",
                                tree_path: "121",
                            },
                            sort: 1,
                            status: true,
                            created_at: "2020-11-04T12:17:56.000000Z",
                            updated_at: "2022-03-17T18:56:09.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "分类管理",
                            value: 128,
                            level: 2,
                        },
                        {
                            id: 213,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "分类类型",
                            code: "categoryTypes",
                            options: {
                                meta: { title: "分类类型" },
                                name: "systems_categories_types",
                                path: "systems/categories/types",
                                file_path: "systems/categoryTypes",
                                tree_path: "0,1",
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-03-17T20:25:57.000000Z",
                            updated_at: "2022-03-17T20:25:57.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "分类类型",
                            value: 213,
                            level: 2,
                        },
                        {
                            id: 230,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "登录日志",
                            code: "login_log3",
                            options: {
                                meta: { title: "登录日志" },
                                name: "login_log",
                                path: "systems/loginlog",
                                file_path: "systems/loginlog",
                                tree_path: "0,1",
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-03-21T09:59:55.000000Z",
                            updated_at: "2022-03-21T10:23:22.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "登录日志",
                            value: 230,
                            level: 2,
                        },
                        {
                            id: 235,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "系统配置",
                            code: "configurations",
                            options: {
                                meta: { title: "系统配置" },
                                name: "configurations",
                                path: "systems/configurations",
                                file_path: "configurations/index",
                                tree_path: "0,1",
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-04-07T18:38:12.000000Z",
                            updated_at: "2022-04-07T18:38:12.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "系统配置",
                            value: 235,
                            level: 2,
                        },
                        {
                            id: 93,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "用户管理",
                            code: "systems_admins",
                            options: {
                                meta: { title: "用户管理" },
                                name: "systems_admins",
                                path: "systems/admins",
                                file_path: "systems/admins",
                                tree_path: "1",
                            },
                            sort: 2,
                            status: true,
                            created_at: "2019-03-03T04:21:21.000000Z",
                            updated_at: "2022-03-21T05:28:30.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "用户管理",
                            value: 93,
                            level: 2,
                        },
                    ],
                    label: "系统",
                    value: 1,
                    level: 1,
                },
                {
                    id: 28989,
                    pid: 0,
                    type: 2,
                    icon: "ant-design:appstore-outlined",
                    name: "更多设置",
                    code: "systems",
                    options: { tree_path: "0" },
                    sort: 4,
                    status: true,
                    created_at: "2018-05-24T19:32:54.000000Z",
                    updated_at: "2021-03-02T03:40:27.000000Z",
                    deleted_at: null,
                    children: [
                        {
                            id: 3,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "节点管理",
                            code: "node",
                            options: {
                                meta: { title: "节点管理" },
                                name: "systems_nodes",
                                path: "systems/nodes",
                                file_path: "systems/nodes",
                                tree_path: "1",
                            },
                            sort: 0,
                            status: true,
                            created_at: "2018-05-24T19:32:54.000000Z",
                            updated_at: "2022-03-20T09:59:24.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "节点管理",
                            value: 3,
                            level: 2,
                        },
                        {
                            id: 95,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "组织机构",
                            code: "systems_departments",
                            options: {
                                meta: { title: "组织机构" },
                                name: "systems_departments",
                                path: "systems/departments",
                                file_path: "systems/departments",
                                tree_path: "1",
                            },
                            sort: 0,
                            status: true,
                            created_at: "2019-03-06T03:55:50.000000Z",
                            updated_at: "2022-03-20T12:27:54.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "组织机构",
                            value: 95,
                            level: 2,
                        },
                        {
                            id: 104,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "角色管理",
                            code: "roles",
                            options: {
                                meta: { title: "角色管理" },
                                name: "systems_roles",
                                path: "systems/roles",
                                file_path: "systems/roles",
                                tree_path: "1",
                            },
                            sort: 0,
                            status: true,
                            created_at: "2019-03-10T23:55:43.000000Z",
                            updated_at: "2022-03-20T11:17:35.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "角色管理",
                            value: 104,
                            level: 2,
                        },
                        {
                            id: 128,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "分类管理",
                            code: "categories",
                            options: {
                                meta: { title: "分类管理" },
                                name: "systems_categories",
                                path: "systems/categories",
                                file_path: "systems/categories",
                                tree_path: "121",
                            },
                            sort: 1,
                            status: true,
                            created_at: "2020-11-04T12:17:56.000000Z",
                            updated_at: "2022-03-17T18:56:09.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "分类管理",
                            value: 128,
                            level: 2,
                        },
                        {
                            id: 213,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "分类类型",
                            code: "categoryTypes",
                            options: {
                                meta: { title: "分类类型" },
                                name: "systems_categories_types",
                                path: "systems/categories/types",
                                file_path: "systems/categoryTypes",
                                tree_path: "0,1",
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-03-17T20:25:57.000000Z",
                            updated_at: "2022-03-17T20:25:57.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "分类类型",
                            value: 213,
                            level: 2,
                        },
                        {
                            id: 230,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "登录日志",
                            code: "login_log3",
                            options: {
                                meta: { title: "登录日志" },
                                name: "login_log",
                                path: "systems/loginlog",
                                file_path: "systems/loginlog",
                                tree_path: "0,1",
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-03-21T09:59:55.000000Z",
                            updated_at: "2022-03-21T10:23:22.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "登录日志",
                            value: 230,
                            level: 2,
                        },
                        {
                            id: 235,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "系统配置",
                            code: "configurations",
                            options: {
                                meta: { title: "系统配置" },
                                name: "configurations",
                                path: "systems/configurations",
                                file_path: "configurations/index",
                                tree_path: "0,1",
                            },
                            sort: 1,
                            status: true,
                            created_at: "2022-04-07T18:38:12.000000Z",
                            updated_at: "2022-04-07T18:38:12.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "系统配置",
                            value: 235,
                            level: 2,
                        },
                        {
                            id: 93,
                            pid: 1,
                            type: 1,
                            icon: "ant-design:appstore-outlined",
                            name: "用户管理",
                            code: "systems_admins",
                            options: {
                                meta: { title: "用户管理" },
                                name: "systems_admins",
                                path: "systems/admins",
                                file_path: "systems/admins",
                                tree_path: "1",
                            },
                            sort: 2,
                            status: true,
                            created_at: "2019-03-03T04:21:21.000000Z",
                            updated_at: "2022-03-21T05:28:30.000000Z",
                            deleted_at: null,
                            children: [],
                            label: "用户管理",
                            value: 93,
                            level: 2,
                        },
                    ],
                    label: "系统",
                    value: 1,
                    level: 1,
                },
            ],
            statuses: [
                {
                    id: 0,
                    value: 0,
                    key: 0,
                    title: "已拒绝",
                },
                {
                    id: 1,
                    value: 1,
                    key: 1,
                    title: "待提审",
                },
                {
                    id: 2,
                    value: 2,
                    key: 2,
                    title: "待审核",
                },
                {
                    id: 2,
                    value: 2,
                    key: 2,
                    title: "待采购",
                },
                {
                    id: 3,
                    value: 3,
                    key: 3,
                    title: "待交付",
                },
                {
                    id: 4,
                    value: 4,
                    key: 4,
                    title: "待确认",
                },
                {
                    id: 5,
                    value: 5,
                    key: 5,
                    title: "已完成",
                },
            ],
            tabBarTabs: [
                {
                    id: 173,
                    pid: 0,
                    type: 1,
                    icon: "ant-design:home-outlined",
                    name: "分析页",
                    code: "dashboard_analysis",
                    options: {},
                    sort: 0,
                    status: true,
                    path: "/consoles/dashboard/analysis",
                    label: "分析页",
                    value: 173,
                    level: 1,
                    selected: true,
                },
            ],

            breadcrumbRoutes: [
                {
                    id: 173,
                    pid: 0,
                    type: 1,
                    icon: "ant-design:home-outlined",
                    name: "分析页",
                    code: "dashboard",
                    options: {},
                    sort: 0,
                    status: true,
                    path: "/consoles/dashboard/analysis",
                    label: "分析页",
                    value: 173,
                    level: 1,
                },
            ],
        };
    },

    getters: {
        getLayoutsConfig(): LayoutsConfig {
            return this.layoutsConfig || ({} as LayoutsConfig);
        },
    },

    actions: {
        msAsiderDrawerVisible(visible:boolean) {
            console.info('toggleAsiderDrawer => store',visible);
          this.layoutsConfig.msLayout.asiderDrawerVisible =  !this.layoutsConfig.msLayout.asiderDrawerVisible
        },
        setLayouts(config: DeepPartial<LayoutsConfig>, scope: string = "ms") {
            console.info("config =>", config);
            console.info("scope =>", scope);

            this.layoutsConfig.msLayout.inlineCollapsed = config.msLayout?.inlineCollapsed;

            // this.layoutsConfig = deepMerge(this.layoutsConfig || {}, config);
            // Persistent.setLocal(LAYOUTS_CFG_KEY, this.layoutsConfig);
            // LAYOUTS_CFG_KEY
        },

        addTabBarTabate(key: number) {
            // let currentData = JSON.parse(localStorage.getItem(`path-data-${key}`));
            let currentData = getAuthCache(`path-data-${key}`);
            // console.info("currentData 4 =>", currentData);
            let currentItem = currentData.slice(-1)[0];
            // console.info("currentItem =>", currentItem);
            localStorage.setItem("last_selected_id", currentItem.id);
            // console.info("currentItem.path  =>",'/consoles/', currentItem.options.path);
            router.push(`/consoles/${currentItem.options.path}`).then(() => {
                localStorage.setItem("current_selected_id", key);
            });
            // console.info("currentData ..0 =>", currentData);

            this.changeBreadcrumbRoutes(currentData);

            this.changeTabBarTabs(currentItem);

            this.menuSelectedKeys = [key];
            return key;
        },
        changeBreadcrumbRoutes(breadcrumbRoutes: any) {
            localStorage.setItem(
                "breadcrumb-routes",
                JSON.stringify(breadcrumbRoutes)
            );
            this.breadcrumbRoutes = breadcrumbRoutes;
        },
        changeTabBarTabs(currentItem: any) {
            let tabBarTabsFindIndex = this.tabBarTabs.findIndex(
                (item) => item.id === currentItem.id
            );

            if (tabBarTabsFindIndex < 0) {
                this.tabBarTabs.forEach((item) => {
                    item.selected = false;
                });
                this.tabBarTabs.push({
                    id: currentItem.id,
                    pid: currentItem.pid,
                    path: currentItem.path,
                    label: currentItem.label,
                    value: currentItem.value,
                    level: currentItem.level,
                    icon: currentItem.icon,
                    name: currentItem.name,
                    selected: true,
                });
            } else {
                this.tabBarTabs.forEach((item) => {
                    item.selected = false;
                });
                this.tabBarTabs[tabBarTabsFindIndex].selected = true;
            }
            localStorage.setItem("tab-bar-tabs", JSON.stringify(this.tabBarTabs));

            console.info("this.tabBarTabs =>", this.tabBarTabs);
        },

        deleteTabBarTabate({ index }) {
            let key = localStorage.getItem("last_selected_id");

            if (
                localStorage.getItem("last_selected_id") ===
                localStorage.getItem("current_selected_id")
            ) {
                key = 173;
            }
            console.info("key =>", key);
            this.tabBarTabs.splice(index, 1);
            let currentData = JSON.parse(localStorage.getItem(`path-data-${key}`));
            let currentItem = currentData.slice(-1)[0];
            localStorage.setItem("last_selected_id", currentItem.id);

            router.push(`/consoles/${currentItem.options.path}`).then(() => {
                localStorage.setItem("current_selected_id", key);
            });

            this.changeBreadcrumbRoutes(currentData);

            this.changeTabBarTabs(currentItem);

            this.menuSelectedKeys = [key];

            return key;
        },
        collapsingMenu() {
            this.collapsed = !this.collapsed;
            this.openKeys = this.collapsed ? [] : this.preOpenKeys;
        },
    },
});

export default useLayoutsStore;
