// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ApplicationSrcAppLogo: typeof import('./../src/components/Application/src/AppLogo.vue')['default']
    ApplicationSrcAppProvider: typeof import('./../src/components/Application/src/AppProvider.vue')['default']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CountDownSrcCountButton: typeof import('./../src/components/CountDown/src/CountButton.vue')['default']
    CountDownSrcCountdownInput: typeof import('./../src/components/CountDown/src/CountdownInput.vue')['default']
    DropdownSrcDropdown: typeof import('./../src/components/Dropdown/src/Dropdown.vue')['default']
    IconSrcIcon: typeof import('./../src/components/Icon/src/Icon.vue')['default']
    IconSrcSvgIcon: typeof import('./../src/components/Icon/src/SvgIcon.vue')['default']
    MenuSrcNavMenu: typeof import('./../src/components/Menu/src/nav-menu.vue')['default']
    MenuSrcNavMenuItem: typeof import('./../src/components/Menu/src/nav-menu-item.vue')['default']
    QrcodeSrcQrcode: typeof import('./../src/components/Qrcode/src/Qrcode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StrengthMeterSrcStrengthMeter: typeof import('./../src/components/StrengthMeter/src/StrengthMeter.vue')['default']
  }
}
