version: "3.9"

services:
  van-nginx:
    image: inlins/lnmp-nginx:latest
    container_name: ims_chin_ink_web
    restart: always
    ports:
      - 8011:80
    environment:
      SERVER_URL: http://ims.chin.ink